# Generated by Django 5.1.3 on 2024-12-06 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_follow_profile_follow_followed_follow_follower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_government_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GovernmentAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
