# Generated by Django 5.1.3 on 2024-11-29 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directmessage',
            options={'ordering': ['-timestamp']},
        ),
    ]
